/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 13/03/2014 10:12:16 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.ElectriCraft.Renders;

import java.util.ArrayList;

import net.minecraft.client.model.ModelRenderer;
import Reika.RotaryCraft.Base.RotaryModelBase;

public class ModelRelay extends RotaryModelBase
{
	//fields
	ModelRenderer Shape1;
	ModelRenderer Shape1a;
	ModelRenderer Shape2;
	ModelRenderer Shape3;
	ModelRenderer Shape3a;
	ModelRenderer Shape4;
	ModelRenderer Shape4a;
	ModelRenderer Shape4b;
	ModelRenderer Shape4c;
	ModelRenderer Shape4d;
	ModelRenderer Shape4e;
	ModelRenderer Shape4f;
	ModelRenderer Shape4h;
	ModelRenderer Shape4i;
	ModelRenderer Shape4j;

	public ModelRelay()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new ModelRenderer(this, 63, 0);
		Shape1.addBox(0F, 0F, 0F, 12, 6, 14);
		Shape1.setRotationPoint(-6F, 16F, -7F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape1a = new ModelRenderer(this, 0, 0);
		Shape1a.addBox(0F, 0F, 0F, 12, 2, 16);
		Shape1a.setRotationPoint(-6F, 22F, -8F);
		Shape1a.setTextureSize(128, 128);
		Shape1a.mirror = true;
		this.setRotation(Shape1a, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 0, 20);
		Shape2.addBox(0F, 0F, 0F, 7, 4, 16);
		Shape2.setRotationPoint(-3.5F, 12F, -8F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 42, 42);
		Shape3.addBox(0F, -2F, 0F, 5, 2, 15);
		Shape3.setRotationPoint(-3.5F, 12F, -7.5F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 2.094395F);
		Shape3a = new ModelRenderer(this, 0, 42);
		Shape3a.addBox(0F, 0F, 0F, 5, 2, 15);
		Shape3a.setRotationPoint(3.5F, 12F, -7.5F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 1.047198F);
		Shape4 = new ModelRenderer(this, 53, 29);
		Shape4.addBox(0F, 0F, 0F, 1, 3, 1);
		Shape4.setRotationPoint(4F, 16F, 7F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape4a = new ModelRenderer(this, 52, 21);
		Shape4a.addBox(0F, 0F, 0F, 8, 6, 1);
		Shape4a.setRotationPoint(-4F, 16F, 7F);
		Shape4a.setTextureSize(128, 128);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 0F, 0F);
		Shape4b = new ModelRenderer(this, 47, 20);
		Shape4b.addBox(0F, 0F, 0F, 1, 6, 1);
		Shape4b.setRotationPoint(5F, 16F, 7F);
		Shape4b.setTextureSize(128, 128);
		Shape4b.mirror = true;
		this.setRotation(Shape4b, 0F, 0F, 0F);
		Shape4c = new ModelRenderer(this, 47, 28);
		Shape4c.addBox(0F, 0F, 0F, 1, 6, 1);
		Shape4c.setRotationPoint(-6F, 16F, 7F);
		Shape4c.setTextureSize(128, 128);
		Shape4c.mirror = true;
		this.setRotation(Shape4c, 0F, 0F, 0F);
		Shape4d = new ModelRenderer(this, 53, 29);
		Shape4d.addBox(0F, 0F, 0F, 1, 3, 1);
		Shape4d.setRotationPoint(-5F, 16F, 7F);
		Shape4d.setTextureSize(128, 128);
		Shape4d.mirror = true;
		this.setRotation(Shape4d, 0F, 0F, 0F);
		Shape4e = new ModelRenderer(this, 47, 20);
		Shape4e.addBox(0F, 0F, 0F, 1, 6, 1);
		Shape4e.setRotationPoint(5F, 16F, -8F);
		Shape4e.setTextureSize(128, 128);
		Shape4e.mirror = true;
		this.setRotation(Shape4e, 0F, 0F, 0F);
		Shape4f = new ModelRenderer(this, 52, 21);
		Shape4f.addBox(0F, 0F, 0F, 8, 6, 1);
		Shape4f.setRotationPoint(-4F, 16F, -8F);
		Shape4f.setTextureSize(128, 128);
		Shape4f.mirror = true;
		this.setRotation(Shape4f, 0F, 0F, 0F);
		Shape4h = new ModelRenderer(this, 47, 28);
		Shape4h.addBox(0F, 0F, 0F, 1, 6, 1);
		Shape4h.setRotationPoint(-6F, 16F, -8F);
		Shape4h.setTextureSize(128, 128);
		Shape4h.mirror = true;
		this.setRotation(Shape4h, 0F, 0F, 0F);
		Shape4i = new ModelRenderer(this, 53, 29);
		Shape4i.addBox(0F, 0F, 0F, 1, 3, 1);
		Shape4i.setRotationPoint(-5F, 16F, -8F);
		Shape4i.setTextureSize(128, 128);
		Shape4i.mirror = true;
		this.setRotation(Shape4i, 0F, 0F, 0F);
		Shape4j = new ModelRenderer(this, 53, 29);
		Shape4j.addBox(0F, 0F, 0F, 1, 3, 1);
		Shape4j.setRotationPoint(4F, 16F, -8F);
		Shape4j.setTextureSize(128, 128);
		Shape4j.mirror = true;
		this.setRotation(Shape4j, 0F, 0F, 0F);
	}

	public void renderAll(ArrayList li, float phi, float theta)
	{
		Shape1.render(f5);
		Shape1a.render(f5);
		Shape2.render(f5);
		Shape3.render(f5);
		Shape3a.render(f5);
		Shape4.render(f5);
		Shape4a.render(f5);
		Shape4b.render(f5);
		Shape4c.render(f5);
		Shape4d.render(f5);
		Shape4e.render(f5);
		Shape4f.render(f5);
		Shape4h.render(f5);
		Shape4i.render(f5);
		Shape4j.render(f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
