/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2017
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 22/09/2016 7:09:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX


package Reika.ElectriCraft.Renders;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;
import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

public class ModelFuse extends RotaryModelBase
{
	//fields
	LODModelPart Shape1a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape4e;
	LODModelPart Shape4f;
	LODModelPart Shape1;
	LODModelPart Shape1c;
	LODModelPart Shape2;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape5;
	LODModelPart Shape5b;

	public ModelFuse()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1a = new LODModelPart(this, 0, 0);
		Shape1a.addBox(0F, 0F, 0F, 12, 5, 16);
		Shape1a.setRotationPoint(-6F, 19F, -8F);
		Shape1a.setTextureSize(128, 128);
		Shape1a.mirror = true;
		this.setRotation(Shape1a, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 42, 42);
		Shape3.addBox(3F, -1F, 0F, 2, 1, 15);
		Shape3.setRotationPoint(-2.5F, 9.5F, -7.5F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 2.356194F);
		Shape3a = new LODModelPart(this, 0, 42);
		Shape3a.addBox(3F, 0F, 0F, 2, 1, 15);
		Shape3a.setRotationPoint(2.5F, 9.5F, -7.5F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 0.7853982F);
		Shape4e = new LODModelPart(this, 52, 31);
		Shape4e.addBox(0F, 0F, 0F, 10, 7, 1);
		Shape4e.setRotationPoint(-5F, 12F, 7F);
		Shape4e.setTextureSize(128, 128);
		Shape4e.mirror = true;
		this.setRotation(Shape4e, 0F, 0F, 0F);
		Shape4f = new LODModelPart(this, 52, 21);
		Shape4f.addBox(0F, 0F, 0F, 10, 7, 1);
		Shape4f.setRotationPoint(-5F, 12F, -8F);
		Shape4f.setTextureSize(128, 128);
		Shape4f.mirror = true;
		this.setRotation(Shape4f, 0F, 0F, 0F);
		Shape1 = new LODModelPart(this, 90, 45);
		Shape1.addBox(0F, 0F, 0F, 1, 6, 16);
		Shape1.setRotationPoint(-6F, 13F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape1c = new LODModelPart(this, 90, 21);
		Shape1c.addBox(0F, 0F, 0F, 1, 6, 16);
		Shape1c.setRotationPoint(5F, 13F, -8F);
		Shape1c.setTextureSize(128, 128);
		Shape1c.mirror = true;
		this.setRotation(Shape1c, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 58, 0);
		Shape2.addBox(0F, 0F, 0F, 9, 1, 15);
		Shape2.setRotationPoint(-4.5F, 11.5F, -7.5F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape4 = new LODModelPart(this, 33, 60);
		Shape4.addBox(0F, 0F, 0F, 2, 1, 14);
		Shape4.setRotationPoint(-1F, 15F, -7F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape4a = new LODModelPart(this, 0, 60);
		Shape4a.addBox(0F, 0F, 0F, 1, 1, 14);
		Shape4a.setRotationPoint(2F, 15F, -7F);
		Shape4a.setTextureSize(128, 128);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 0F, 0F);
		Shape4b = new LODModelPart(this, 0, 60);
		Shape4b.addBox(0F, 0F, 0F, 1, 1, 14);
		Shape4b.setRotationPoint(-3F, 15F, -7F);
		Shape4b.setTextureSize(128, 128);
		Shape4b.mirror = true;
		this.setRotation(Shape4b, 0F, 0F, 0F);
		Shape5b = new LODModelPart(this, 0, 77);
		Shape5b.addBox(0F, 0F, 0F, 13, 1, 17);
		Shape5b.setRotationPoint(-6.5F, 22F, -8.5F);
		Shape5b.setTextureSize(128, 128);
		Shape5b.mirror = true;
		this.setRotation(Shape5b, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 0, 77);
		Shape5.addBox(0F, 0F, 0F, 13, 1, 17);
		Shape5.setRotationPoint(-6.5F, 20F, -8.5F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float theta, float phi)
	{
		Shape1a.render(te, f5);

		Shape5.render(te, f5);
		Shape5b.render(te, f5);

		Shape4e.render(te, f5);
		Shape4f.render(te, f5);

		Shape3.render(te, f5);
		Shape3a.render(te, f5);

		Shape4.render(te, f5);
		Shape4a.render(te, f5);
		Shape4b.render(te, f5);

		Shape1.render(te, f5);
		Shape1c.render(te, f5);

		Shape2.render(te, f5);
	}

}
